[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[tools]
doctl = "latest"
"go:github.com/schollz/croc/v10" = "latest"
hcloud = "latest"
helm = "latest"
k9s = "latest"
kubectx = "latest"
"npm:@beads/bd" = "latest"
ruby = "latest"

